# Project identification
sonar.projectKey=Blueray-Automation_quantum-notification-sms-gateway-service_087d4488-d085-4ea3-8aba-b0aaa99d3233

# Language
sonar.language=py
sonar.sourceEncoding=UTF-8

# Paths
sonar.sources=.
sonar.exclusions=tests/**, migrations/**
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.python.coverage.reportPaths=coverage.xml

# Wait for quality gate
sonar.qualitygate.wait=true
