"""drop nullable constraints

Revision ID: 4df8ce17b442
Revises: 52ceabffe697
Create Date: 2025-10-01 11:19:23.308956

"""

# revision identifiers, used by Alembic.
revision = "4df8ce17b442"
down_revision = "52ceabffe697"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
