import enum
from config import (
    APPLICATION_NAME,
    TESTING_ENVIRONMENT,
    PRODUCTION_ENVIRONMENT,
    DEVELOPMENT_ENVIRONMENT,
    UAT_ENVIRONMENT,
    ENV_ERROR,
    LOG_HEADER,
    SortResultEnum,
)