"""add nullable constraints

Revision ID: 2bc4858c0419
Revises: 4df8ce17b442
Create Date: 2025-10-01 11:20:42.893353

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2bc4858c0419"
down_revision = "4df8ce17b442"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resources") as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            nullable=True,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resources") as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),
        )
    # ### end Alembic commands ###