"""add nullable constraints

Revision ID: 76c39652c002
Revises: 2bc4858c0419
Create Date: 2025-10-01 11:21:34.942680

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "76c39652c002"
down_revision = "2bc4858c0419"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resources") as batch_op:
        batch_op.alter_column("created_by", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("updated_at", existing_type=sa.DateTime(), nullable=True)
        batch_op.alter_column("updated_by", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("deleted_by", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("deleted_at", existing_type=sa.DateTime(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resources") as batch_op:
        batch_op.alter_column("deleted_at", existing_type=sa.DateTime(), nullable=False)
        batch_op.alter_column("deleted_by", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("updated_by", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=sa.DateTime(), nullable=False)
        batch_op.alter_column("created_by", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###