/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Brand colors from UI screens
        'neural-purple': '#A855F7',
        'neural-indigo': '#6366F1',
        'accent-emerald': '#10B981',
        'neural-rose': '#FB7185',
        
        // Semantic colors (dark mode - primary theme from AI chat screen)
        'background': '#000000',
        'surface': '#000000',
        'surface-panel': '#09090B',
        'surface-card': '#09090B',
        'surface-container': '#18181B',
        'surface-container-low': '#121212',
        'surface-container-high': '#1C1C1F',
        'surface-container-highest': '#27272A',
        'surface-container-lowest': '#000000',
        'surface-dim': '#09090B',
        'surface-bright': '#18181B',
        'surface-variant': '#27272A',
        'surface-tint': '#A1A1AA',
        
        'on-surface': '#FFFFFF',
        'on-surface-variant': '#A1A1AA',
        'on-background': '#FFFFFF',
        'on-primary': '#000000',
        'on-primary-container': '#000000',
        'on-primary-fixed': '#000000',
        'on-primary-fixed-variant': '#000000',
        'on-secondary': '#000000',
        'on-secondary-container': '#A1A1AA',
        'on-secondary-fixed': '#1B1C1C',
        'on-secondary-fixed-variant': '#A1A1AA',
        'on-tertiary': '#000000',
        'on-tertiary-container': '#71717A',
        'on-tertiary-fixed': '#FFFFFF',
        'on-tertiary-fixed-variant': '#A1A1AA',
        'on-error': '#FFFFFF',
        'on-error-container': '#93000A',
        
        'primary': '#FFFFFF',
        'primary-container': '#FFFFFF',
        'primary-fixed': '#E2E2E2',
        'primary-fixed-dim': '#C6C6C6',
        'inverse-primary': '#000000',
        
        'secondary': '#A1A1AA',
        'secondary-container': '#27272A',
        'secondary-fixed': '#E4E2E2',
        'secondary-fixed-dim': '#C7C6C6',
        'inverse-surface': '#F1F1EF',
        'inverse-on-surface': '#2F3130',
        
        'tertiary': '#FFFFFF',
        'tertiary-container': '#1B1B1B',
        'tertiary-fixed': '#E2E2E2',
        'tertiary-fixed-dim': '#C6C6C6',
        
        'error': '#BA1A1A',
        'error-container': '#FFDAD6',
        
        'outline': '#52525B',
        'outline-variant': '#3F3F46',
        'border-subtle': 'rgba(255, 255, 255, 0.1)',
        
        // Light mode semantic colors (from landing/pricing/enterprise screens)
        'light-background': '#F9F9F7',
        'light-surface': '#F9F9F7',
        'light-surface-panel': '#F3F2EF',
        'light-surface-card': '#FCFCFB',
        'light-surface-container': '#EEEEEC',
        'light-surface-container-low': '#F4F4F2',
        'light-surface-container-high': '#E8E8E6',
        'light-surface-container-highest': '#E2E3E1',
        'light-surface-container-lowest': '#FFFFFF',
        'light-surface-dim': '#DADAD8',
        'light-surface-bright': '#F9F9F7',
        'light-surface-variant': '#E2E3E1',
        'light-surface-tint': '#5E5E5E',
        
        'light-on-surface': '#1A1C1B',
        'light-on-surface-variant': '#4C4546',
        'light-on-background': '#1A1C1B',
        'light-on-primary': '#FFFFFF',
        'light-on-primary-container': '#848484',
        'light-on-primary-fixed': '#1B1B1B',
        'light-on-primary-fixed-variant': '#474747',
        'light-on-secondary': '#FFFFFF',
        'light-on-secondary-container': '#626262',
        'light-on-secondary-fixed': '#1B1C1C',
        'light-on-secondary-fixed-variant': '#464747',
        'light-on-tertiary': '#FFFFFF',
        'light-on-tertiary-container': '#848484',
        'light-on-tertiary-fixed': '#1B1B1B',
        'light-on-tertiary-fixed-variant': '#474747',
        'light-on-error': '#FFFFFF',
        'light-on-error-container': '#93000A',
        
        'light-primary': '#000000',
        'light-primary-container': '#1B1B1B',
        'light-primary-fixed': '#E2E2E2',
        'light-primary-fixed-dim': '#C6C6C6',
        'light-inverse-primary': '#C6C6C6',
        
        'light-secondary': '#5E5E5E',
        'light-secondary-container': '#E1DFDF',
        'light-secondary-fixed': '#E4E2E2',
        'light-secondary-fixed-dim': '#C7C6C6',
        'light-inverse-surface': '#2F3130',
        'light-inverse-on-surface': '#F1F1EF',
        
        'light-tertiary': '#000000',
        'light-tertiary-container': '#1B1B1B',
        'light-tertiary-fixed': '#E2E2E2',
        'light-tertiary-fixed-dim': '#C6C6C6',
        
        'light-error': '#BA1A1A',
        'light-error-container': '#FFDAD6',
        
        'light-outline': '#7E7576',
        'light-outline-variant': '#CFC4C5',
        'light-border-subtle': '#E7E7E4',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        gutter: '32px',
        margin: '32px',
        'section-gap-desktop': '180px',
        'section-gap-mobile': '80px',
        'max-width': '1280px',
      },
      fontFamily: {
        'h1': ['Geist', 'Inter', 'sans-serif'],
        'h1-mobile': ['Geist', 'Inter', 'sans-serif'],
        'h2': ['Geist', 'Inter', 'sans-serif'],
        'h3': ['Geist', 'Inter', 'sans-serif'],
        'body-lg': ['Geist', 'Inter', 'sans-serif'],
        'body-md': ['Geist', 'Inter', 'sans-serif'],
        'label-caps': ['Geist', 'Inter', 'sans-serif'],
        'mono-metrics': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'h1': ['84px', { lineHeight: '1.05', letterSpacing: '-0.04em', fontWeight: '600' }],
        'h1-mobile': ['48px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '600' }],
        'h2': ['64px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '600' }],
        'h3': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
        'mono-metrics': ['12px', { lineHeight: '1', letterSpacing: '0', fontWeight: '700' }],
      },
      boxShadow: {
        'inner-glow': 'inset 0 0 0 1px rgba(255, 255, 255, 0.05)',
        'neural-glow': '0 0 20px rgba(168, 85, 247, 0.3)',
        'neural-glow-lg': '0 0 40px rgba(168, 85, 247, 0.4)',
        'pro-card': '0 0 40px -10px rgba(168, 85, 247, 0.3)',
      },
      backgroundImage: {
        'neural-gradient': 'radial-gradient(circle at 20% 30%, rgba(168, 85, 247, 0.1) 0%, transparent 40%), radial-gradient(circle at 80% 70%, rgba(99, 102, 241, 0.1) 0%, transparent 40%)',
        'pro-gradient-border': 'linear-gradient(135deg, #A855F7, #6366F1)',
        'glass-gradient': 'linear-gradient(135deg, rgba(255,255,255,0.05) 0%, rgba(255,255,255,0.02) 100%)',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'marquee': 'marquee-scroll 40s linear infinite',
        'marquee-reverse': 'marquee-scroll 40s linear infinite reverse',
        'spin-slow': 'spin 60s linear infinite',
        'spin-reverse': 'spin 40s linear infinite reverse',
        'pulse-slow': 'pulse 4s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'marquee-scroll': {
          '0%': { transform: 'translateX(-50%)' },
          '100%': { transform: 'translateX(0%)' },
        },
      },
      backdropBlur: {
        '3xl': '64px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}